Metrics API doc fixup
dcos/dcos-docs pull request #1017
Opened 2017-04-11 21:19 UTC by joel-hamill

## Description

https://jira.mesosphere.com/browse/DOCS-1816

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-04-11 21:24 UTC, karlkfi commented on 1.9/administration/monitoring/metrics/index.md
> +The [metrics HTTP API](/docs/1.9/monitoring/metrics/metrics-api/) exposes these areas.
> The [Metrics API](/docs/1.9/monitoring/metrics/metrics-api/) exposes these areas.

2017-04-11 21:25 UTC, karlkfi commented on 1.9/administration/monitoring/metrics/index.md
> +For more information on which metrics are collected, see the Metrics [reference](/docs/1.9/administration/monitoring/metrics/reference/).
> For more information on which metrics are collected, see the [Metrics Reference](/docs/1.9/administration/monitoring/metrics/reference/).

2017-04-11 21:27 UTC, karlkfi commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +You can use the Metrics API to periodically poll for data about your cluster, hosts, containers, and applications. You can then pass this data to a third party service of your choice to achieve infor
poll or stream?

2017-04-11 21:32 UTC, karlkfi commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +You can use the Metrics API to periodically poll for data about your cluster, hosts, containers, and applications. You can then pass this data to a third party service of your choice to achieve infor
nevermind. there's no streaming in this api

2017-04-11 21:33 UTC, karlkfi commented on 1.9/administration/monitoring/metrics/reference.md
> +post_title: Metrics Statistics Reference
is this really the right title? aren't they just metrics, not metrics statistics... metrics attributes, maybe?

2017-04-11 21:37 UTC, joel-hamill commented on 1.9/administration/monitoring/metrics/reference.md
> +post_title: Metrics Statistics Reference
`Metrics Reference` is probably fine.

2017-04-12 20:17 UTC, guenter requested changes

2017-04-12 20:17 UTC, guenter commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +Access to the Metrics API is proxied through the Admin Router on each node.
Afaik admin router is not involved here. You connect to localhost:61001 instead.

2017-04-12 20:17 UTC, guenter commented on 1.9/administration/monitoring/metrics/reference.md
> +| cpus_limit    | The number of CPUs allocated. |
number of CPU shares allocated

2017-04-12 20:17 UTC, guenter commented on 1.9/administration/monitoring/metrics/reference.md
> +| cpus_system_time_secs    | Total CPU time spent in kernal mode in seconds. |
kernel

2017-04-12 21:01 UTC, guenter commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +Access to the Metrics API is proxied through the Admin Router on each node.
I understand this now. Admin router is in fact the thing that's listening on localhost:61001. I didn't know this implementation detail and assumed that the routes are available on the public master IP, which is how I usually interact with AR. I suggest we don't mention the fact that it's admin router and just say connect to :61001 on the agent.

2017-04-13 21:52 UTC, joel-hamill commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +Access to the Metrics API is proxied through the Admin Router on each node.
@guenter https://github.com/dcos/dcos-docs/pull/1017/commits/3b087908771b3ee51d650610f9e3d03cded29534

2017-04-14 17:47 UTC, sascala reviewed
Some edits but otherwise LGTM

2017-04-14 17:47 UTC, sascala commented on 1.9/administration/monitoring/metrics/index.md
> +Per-container metrics tags enable you to arbitrarily group metrics, for example on a per-framework or per-system, or agent basis. Here are the available tags:
suggest: "...for example, on a per-framework, per-system, or agent basis."

2017-04-14 17:47 UTC, sascala commented on 1.9/administration/monitoring/metrics/index.md
>  DC/OS applications will discover the endpoint via an environment variable (`STATSD_UDP_HOST` or `STATSD_UDP_PORT`). Applications leverage this StatsD interface to send custom profiling metrics to the
s/leverage/use

2017-04-14 17:47 UTC, sascala commented on 1.9/administration/monitoring/metrics/metrics-api.md
> -Access to the Metrics API is proxied through the Admin Router on each node using the following route:
"is the Metrics API resource path."

2017-04-14 17:47 UTC, sascala commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +From outside of the cluster, you can access by using this path, where `<resource-path>` is Metrics API resource path.
"the Metrics API resource path."

2017-04-14 17:56 UTC, joel-hamill commented on 1.9/administration/monitoring/metrics/metrics-api.md
> +From outside of the cluster, you can access by using this path, where `<resource-path>` is Metrics API resource path.
fixed

2017-04-14 18:01 UTC, merged