Add dns_bind_ip_blacklist and dns_forward_zones
dcos/dcos-docs pull request #1043
Opened 2017-05-02 23:34 UTC by nlsun

## Description

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-05-02 23:35 UTC, nlsun commented
I've separated it into 2 commits, the second commit contains my changes.

2017-05-02 23:39 UTC, nlsun commented
@joel-hamill ready for review

2017-05-03 17:58 UTC, joel-hamill requested changes

2017-05-03 17:58 UTC, joel-hamill commented on 1.10/installing/custom/configuration-parameters.md
> +This parameter is used by DC/OS DNS resolvers to configure the forwarding of queries for DNS addresses in a particular DNS zone to a custom DNS resolver.
How about: `This parameter specifies a YAML nested list (`-`) of DNS addresses and zones whose query requests are forwarded to a custom resolver.`

2017-05-03 17:58 UTC, joel-hamill commented on 1.10/installing/custom/configuration-parameters.md
> +This takes the form of nested lists. For example:
Think you can remove `This takes the form of nested lists.`

2017-05-03 23:53 UTC, nlsun commented
@joel-hamill made the changes

2017-05-05 16:54 UTC, joel-hamill approved these changes

2017-05-05 16:54 UTC, merged