Ss/pods vols clarification
dcos/dcos-docs pull request #1052
Opened 2017-05-10 16:34 UTC by sascala

## Description
https://jira.mesosphere.com/browse/DOCS-1890

This is a tiny clarification, but the reporter marked it as a blocker, so, it's a blocker here too

## Urgency
- [X] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-05-11 16:21 UTC, joel-hamill requested changes

2017-05-11 16:21 UTC, joel-hamill commented on 1.9/deploying-services/pods/technical-overview.md
> +**Note:** Data does not persist if a pod is restarted.
`...pods are restarted.`

2017-05-16 13:29 UTC, sascala commented on 1.9/deploying-services/pods/technical-overview.md
> +**Note:** Data does not persist if a pod is restarted.
👍

2017-05-16 16:49 UTC, joel-hamill approved these changes

2017-05-16 16:49 UTC, merged