Improve external volumes examples
dcos/dcos-docs pull request #1054
Opened 2017-05-11 20:22 UTC by sascala

## Description
Have the external volumes examples actually employ volumes
https://jira.mesosphere.com/browse/DOCS-1505

## Urgency
- [X] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-05-12 08:41 UTC, gpaul requested changes
I noticed that the commands are wrong.

If you'd like to test that it is correct now and was wrong before, spin up a cluster on CCM. 

Next, use the following CMD instead.

```
"cmd": "date >> test-rexray-volume/test.txt; cat test-rexray-volume/test.txt",
```
(It's important to use the '>>' or "append" operator for this test.)

If the external volume is being used correctly, the logs of successive runs of the application will show more and more lines as part of the `cat` operation.

Finally, submit the app definition and wait for it to run - it should run several times and every time the list of dates printed to the stdout log of the instances should grow longer. If it doesn't it means that the `test.txt` file is not being persisted between runs and the config is wrong.

The same test holds for the docker containerizer, but the paths should be `/data/test-rexray-volume/test.txt` instead.

2017-05-12 08:41 UTC, gpaul commented on 1.9/storage/external-storage.md
> +      "cmd": "mkdir my-test-vol && touch my-test-vol/test.txt && ls my-test-vol/",
I believe this should be 
```
mkdir test-rexray-volume/test-dir && touch test-rexray-volume/test-dir/test.txt && ls test-rexray-volume/test-dir/
```

The `my-test-vol` property that is specified for this volume is the name of the volume in eg., your AWS account, and is unrelated to the directory path in the container. The directory path in the container is given by the `containerPath` property, which in this case is `test-rexray-volume`.

2017-05-12 08:41 UTC, gpaul commented on 1.9/storage/external-storage.md
> +      "cmd": "mkdir my-test-vol && touch my-test-vol/test.txt && ls my-test-vol/",
I believe this should be 
```
mkdir /data/test-rexray-volume/test-dir && touch /data/test-rexray-volume/test-dir/test.txt && ls /data/test-rexray-volume/test-dir/
```

The directory path in the container is given by the `containerPath` property, which in this case is `/data/test-rexray-volume`. Note that it is an absolute path in this case, as this is using the Docker containerizer, which expects absolute paths for `containerPath` and mounts the external volume at exactly the given path in the container.

2017-05-26 21:14 UTC, sascala commented
Thank you for the suggested command, @gpaul . I've changed the command and added explanatory text.

2017-05-29 12:54 UTC, gpaul approved these changes
LGTM :+1:

2017-06-01 19:14 UTC, merged