Added direct lvm recommendation
dcos/dcos-docs pull request #697
Opened 2016-10-21 21:43 UTC by joel-hamill

## What are your changes?
Added direct lvm recommendation
## What type of changes does your doc introduce?
- [ ] Bug fix
- [x] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have tested all commands and code snippets.
- [ ] I have built locally and tested for broken links and formatting.
- [ ] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [ ] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

Ping @emanic @sascala @joel-hamill for reviewing pull request changes.

## If you included a comment with your commit, it appears here:

2016-10-21 21:59 UTC, cmaloney requested changes

2016-10-21 21:59 UTC, cmaloney commented on 1.7/administration/installing/custom/system-requirements/install-docker-centos.md
> +* Use `direct-lvm` as the method to access Docker backing store in production. For more information, see [Selecting a Storage Driver](https://docs.docker.com/engine/userguide/storagedriver/selectadri
This conflicts with the "Format node storage as XFS" and "overlayfs" instructions throughout the rest of this.

2016-10-24 18:39 UTC, joel-hamill commented on 1.7/administration/installing/custom/system-requirements/install-docker-centos.md
> +* Use `direct-lvm` as the method to access Docker backing store in production. For more information, see [Selecting a Storage Driver](https://docs.docker.com/engine/userguide/storagedriver/selectadri
@cmaloney so should this line not be added, or should we revise the rest of the doc?

2016-10-24 20:22 UTC, cmaloney commented on 1.7/administration/installing/custom/system-requirements/install-docker-centos.md
> +* Use `direct-lvm` as the method to access Docker backing store in production. For more information, see [Selecting a Storage Driver](https://docs.docker.com/engine/userguide/storagedriver/selectadri
We should document Direct-LVM as the most production ready / stable on CentOS. That requires that the rest of this document be re-written / re-worked (Just adding a bullet makes the documentation inconsistent with itself).

2016-10-24 20:36 UTC, joel-hamill commented on 1.7/administration/installing/custom/system-requirements/install-docker-centos.md
> +* Use `direct-lvm` as the method to access Docker backing store in production. For more information, see [Selecting a Storage Driver](https://docs.docker.com/engine/userguide/storagedriver/selectadri
@karlkfi ^^

2016-10-25 18:31 UTC, karlkfi commented on 1.7/administration/installing/custom/system-requirements/install-docker-centos.md
> +* Use `direct-lvm` as the method to access Docker backing store in production. For more information, see [Selecting a Storage Driver](https://docs.docker.com/engine/userguide/storagedriver/selectadri
Sounds reasonable to me, but I haven't tested Direct-LVM, don't know why we're recommending it, and don't know if it works with docker-in-docker (aka Jenkins). If eng wants to change the recommendation then they should change the docs to reflect that.

2016-10-25 20:03 UTC, joel-hamill commented
@cmaloney @karlkfi Okay, if we don't want to change that's fine. I was working off this internal JIRA from support: https://mesosphere.atlassian.net/browse/DOCS-1052.

2016-10-25 22:00 UTC, karlkfi commented
@joel-hamill: changing the recommendation in not something that should be taken lightly. We need buy-in from engineering that they are testing this in CI and support that they are willing to support it going forward. Just because Docker recommends it, doesn't mean we need to blindly recommend the same. And if we do want to recommend it then we need proof (manual and automated testing) that it passes all known use cases.

I'm not saying we don't want to change it. I'm saying there is a cost to changing it and we haven't paid it yet or even promised to pay it.

I would like to see buy-in from @spahl & @graham-murphy before we change the recommendations. And when we do, we need to change it everywhere.

2016-10-31 15:23 UTC, closed without merging