Added clean agent procedure
dcos/dcos-docs pull request #719
Opened 2016-11-01 21:33 UTC by joel-hamill

## What are your changes?
- Fixed up TOC to fit new topic
## What type of changes does your doc introduce?
- [ ] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have tested all commands and code snippets.
- [ ] I have built locally and tested for broken links and formatting.
- [ ] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [ ] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

2016-11-01 21:34 UTC, joel-hamill commented
@cmaloney see `1.8/administration/remove-agent.md`

2016-11-02 20:31 UTC, cmaloney requested changes

2016-11-02 20:31 UTC, cmaloney commented on 1.8/administration/remove-agent.md
> +1.  [SSH](/docs/1.8/administration/access-node/sshcluster/) to the master node.
This needs to be sshing to the individual agent the user wants to de-register.

2016-11-02 20:41 UTC, joel-hamill commented
@sascala ready for merge

2016-11-02 21:05 UTC, sascala reviewed
I had two questions, but otherwise LGTM

2016-11-02 21:05 UTC, sascala commented on 1.9/administration/upgrading.md
> +- You should take a snapshot of ZooKeeper prior to upgrading. Marathon supports rollbacks, but does not support downgrades.
Do we have instructions for this?

2016-11-02 21:05 UTC, sascala commented on 1.9/administration/upgrading.md
> +- Overlay networks require Docker 1.11. For more information, see the [documentation](/docs/1.9/administration/overlay-networks/).
Are overlay networks new? Or do you mean if you're upgrading with overlay networks? or both? More generally, what is the context?

2016-11-02 23:10 UTC, joel-hamill commented on 1.9/administration/upgrading.md
> +- Overlay networks require Docker 1.11. For more information, see the [documentation](/docs/1.9/administration/overlay-networks/).
Not new, but as you're upgrading DCOS you might be tempted to use a different docker version, and the overlay networks feature.

2016-11-03 20:59 UTC, merged