added community contribution to jobs cli doc
dcos/dcos-docs pull request #843
Opened 2017-01-09 23:35 UTC by sascala

## What are your changes?

## What type of changes does your doc introduce?
- [X] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [X] High
- [ ] Medium

## I have completed these items:
- [X] I have tested all commands and code snippets.
- [ ] I have built locally and tested for broken links and formatting.
- [X] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [X] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

Ping `@emanic`, `@sascala`, or `@joel-hamill` for reviewing pull request changes.

## If you included a comment with your commit, it appears here:

2017-01-09 23:48 UTC, sascala commented
@joel-hamill I updated the CLI docs to include the community contribution and made the changes for 1.9 as well.

2017-01-10 18:39 UTC, joel-hamill commented on 1.8/usage/jobs/getting-started.md
> +To get the log for a only a specific job run, use a job run ID from `dcos job history <job-id>`
Typo: `...for a specific job run...`

2017-01-10 18:41 UTC, joel-hamill commented on 1.9/usage/jobs/examples.md
> +**Note:** This example JSON only works when you add the job from the DC/OS CLI or the UI. Use the [example below](#schedule-with-api) to create a scheduled job via the API.
Line 37 says `via the DC/OS CLI`. Line 38 begins by saying the `CLI or the UI`. Please clean this up.

2017-01-10 18:42 UTC, joel-hamill reviewed
Added comment inline

2017-01-10 18:43 UTC, joel-hamill requested changes
Added comments inline.

2017-01-10 18:54 UTC, sascala commented on 1.9/usage/jobs/examples.md
> +**Note:** This example JSON only works when you add the job from the DC/OS CLI or the UI. Use the [example below](#schedule-with-api) to create a scheduled job via the API.
These are instructions for creating a job with a schedule from the CLI. But the note accurately states that jobs with schedules can be created with the CLI and the UI, just not the API. I could take out the mention of the UI, but then I'd be implying that you can't create scheduled jobs that way.

2017-01-10 19:00 UTC, sascala commented on 1.9/usage/jobs/examples.md
> +**Note:** This example JSON only works when you add the job from the DC/OS CLI or the UI. Use the [example below](#schedule-with-api) to create a scheduled job via the API.
I removed "via the DC/OS CLI".

2017-01-10 19:01 UTC, sascala commented
@joel-hamill I made your changes -- thank you for the review.

2017-01-10 19:28 UTC, merged