Addresses issue DCOS-632. Documentation Updated
dcos/dcos-docs pull request #885
Opened 2017-02-01 21:22 UTC by Rohithzr

## What are your changes?
Added following steps that are required to make custom Auth0 Work.
1. Changes that need to be done in the custom login page.
2. Mentioned to use Custom Social Provider API Keys.

Hosted a page on github pages as a helper to generate the encoded config string

## What type of changes does your doc introduce?
- [x] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [x] Medium

## I have completed these items:
- [x] I have tested all commands and code snippets.
- [x] I have built locally and tested for broken links and formatting.
- [x] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [x] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

@joel-hamill

2017-02-01 21:32 UTC, judithpatudith commented
@joel-hamill A community member just submitted a docs patch, can you shepherd it in for them? Thank you!

2017-02-03 00:13 UTC, joel-hamill commented
@alberts can you review this for technical accuracy?

2017-02-03 01:18 UTC, alberts commented
lgtm. @jgehrcke for one last look.

2017-02-03 01:18 UTC, alberts commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +If you don't setup your own social provider keys you will get an error saying "Social provider API keys are required"
full stop?

2017-02-03 11:24 UTC, jgehrcke requested changes
Thanks, @Rohithzr -- this is nice to see. 

I have left two suggestions for grammar improvement. Would appreciate if you could go through them and modify the 1.7/1.8/1.9 docs equivalently.

Cheers

2017-02-03 11:24 UTC, jgehrcke commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +To obtain the client ID and using your own Auth0 account, complete the following steps:
"... and to use your own ... "? (grammar)

2017-02-03 11:24 UTC, jgehrcke commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +6. Create a custom Login Page in Auth0 "Hosted Pages" Tab, using the HTML/JavaScript source of
`in Auth0's "Hosted Pages" Tab`? (grammar)

2017-02-03 11:39 UTC, Rohithzr commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +To obtain the client ID and using your own Auth0 account, complete the following steps:
@jgehrcke ok how does this look?

> To obtain the client ID and use your own Auth0 account, complete the following steps:

2017-02-03 11:45 UTC, Rohithzr commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +6. Create a custom Login Page in Auth0 "Hosted Pages" Tab, using the HTML/JavaScript source of
@jgehrcke ok how does this look?

> In [Auth0's Hosted Pages](https://manage.auth0.com/#/login_page), Create a custom Login Page using the HTML/JavaScript source of...

2017-02-03 11:53 UTC, jgehrcke commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +To obtain the client ID and using your own Auth0 account, complete the following steps:
I think this looks great! :)

2017-02-03 11:53 UTC, jgehrcke commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +6. Create a custom Login Page in Auth0 "Hosted Pages" Tab, using the HTML/JavaScript source of
Looks great! (but `Create` must be `create` then).

2017-02-03 11:55 UTC, Rohithzr commented on 1.7/administration/id-and-access-mgt/configure-your-security.md
> +6. Create a custom Login Page in Auth0 "Hosted Pages" Tab, using the HTML/JavaScript source of
ok so i'll push the changes
Thanks

2017-02-03 20:17 UTC, Rohithzr commented on 1.8/administration/id-and-access-mgt/configure-your-security.md
done

2017-02-03 20:17 UTC, Rohithzr commented on 1.9/administration/id-and-access-mgt/configure-your-security.md
done

2017-02-03 20:18 UTC, Rohithzr commented
@jgehrcke @joel-hamill @alberts I think I have implemented all your suggestions. Please verify the same.

Thanks.

2017-02-03 23:32 UTC, joel-hamill approved these changes

2017-02-09 10:46 UTC, Rohithzr commented
@joel-hamill @jgehrcke this is ready to be merged, I hope.

2017-02-09 11:44 UTC, jgehrcke approved these changes

2017-02-09 21:58 UTC, merged

2017-02-11 18:45 UTC, jgehrcke commented
@Rohithzr, thanks for the contribution!

2019-06-11 19:59 UTC, Rohithzr commented
There is no current documentation to achive this anymore, is changing the Auth0 client no longer possible?