warning about ext vol size
dcos/dcos-docs pull request #908
Opened 2017-02-21 21:23 UTC by sascala

## Description

## Urgency
- [X] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-02-21 21:23 UTC, sascala commented
@joel-hamill What do you think about the aesthetics of this? Should it be all bold?

2017-02-22 03:06 UTC, jdef requested changes

2017-02-22 03:06 UTC, jdef commented on 1.9/usage/storage/external-storage.md
> +**Warning:** Volume size is specified in GB. There is currently an inaccuracy in the DC/OS GUI where the volume size is marked in MiB. When creating a volume, make sure you specify the number of **GB
nit: let's be consistent, if we're using `MiB` then we should also use `GiB` instead of `GB`

2017-02-22 03:06 UTC, jdef commented on 1.9/usage/storage/external-storage.md
> +volume size unit to MiB. However, Marathon still regards the size as GB and forward it directly to Mesos.
ditto

2017-02-23 20:23 UTC, jdef approved these changes
Lgtm

2017-02-24 23:28 UTC, merged