upgrade to containerizers section
dcos/dcos-docs pull request #953
Opened 2017-03-13 23:27 UTC by sascala

## Description

## Urgency
- [ ] Blocker 
- [X] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-03-31 21:38 UTC, joel-hamill commented on 1.8/usage/containerizers/index.md
> +DC/OS supports the Mesos containerizer types :
extra space after `types`

2017-03-31 21:38 UTC, joel-hamill commented on 1.8/usage/containerizers/index.md
> +- The [DC/OS Universal Container Runtime](/docs/1.8/usage/containerizers/ucr/)
missing period

2017-04-25 00:18 UTC, joel-hamill requested changes
You must have `nav_title`, but `post_title` is optional.  Some of the files are missing `post-title`.

2017-04-25 22:21 UTC, sascala commented
@joel-hamill I think I got all your comments

2017-04-27 16:59 UTC, joel-hamill approved these changes

2017-04-27 17:08 UTC, merged