private docker registry doc
dcos/dcos-docs pull request #995
Opened 2017-03-28 22:59 UTC by sascala

## Description

## Urgency
- [ ] Blocker 
- [X] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

2017-03-28 23:00 UTC, sascala commented
@Gilbert88 I'm pretty sure this doc is correct -- I was able to test it successfully until the last step, when my cluster gave me this error: `
Failed to launch container: Failed to fetch all URIs for container '89fcb0a5-fa19-4715-954e-ad893e507253' with exit status: 256`

I'm assuming this is an error or oversight on my part?

2017-04-14 17:02 UTC, joel-hamill requested changes

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +1. Check you have both files in the tar.
`Verify that both files are in the archive file. `

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +
This topic needs an introduction. Right now it immediately jumps into the task without context. 
- where does the `docker.tar.gz` file come from?
- where does the `uris` field come from? what app? is this a marathon app definition parameter?

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +1. Tar this folder and its contents.
Compress the `.docker` folder and its contents.

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +1. Put the gzipped file in location that you will then reference in your application definition.
`Put the archive file in a location that is accessible by your application definition.`

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +    **Important:** The URI you create must be accessible by all nodes that may start your application. You can distribute the
`The URI must be accessible by all nodes that will start your application. `

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +1. Add the path to the gzipped login credentials to your Marathon app definition
`Add the path to the archive file login credentials to your app definition.`

2017-04-14 17:02 UTC, joel-hamill commented on 1.9/usage/managing-services/private-docker-registry.md
> +1. The Docker image will now pull using the security credentials you provided.
`... that you specified.`

2017-04-17 16:54 UTC, sascala commented on 1.9/usage/managing-services/private-docker-registry.md
> +1. Put the gzipped file in location that you will then reference in your application definition.
I don't know that it's a question of accessibility -- I think when you add the app definition to Marathon, the file will be pulled from wherever on your local machine you specify.

2017-04-17 16:58 UTC, sascala commented
@joel-hamill Changes made

2017-04-17 20:13 UTC, joel-hamill approved these changes

2017-04-17 20:14 UTC, merged